language: java

os: linux

env:
  global:
    - HADOOP_ADDRESS=hdfs://localhost:9000

sudo: required

jdk:
  - oraclejdk8

before_install:
    - wget http://mirrors.tuna.tsinghua.edu.cn/apache/hadoop/common/hadoop-2.7.4/hadoop-2.7.4.tar.gz
    - sudo tar -xzvf hadoop-2.7.4.tar.gz
    - sudo sh hadoop-2.7.4/sbin/start-dfs.sh

script: mvn clean install cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)